---
- name: Enable ElasticSearch
  service:
    name: elasticsearch
    enabled: yes

- name: Reload Systemd
  systemd: daemon_reload=yes

- name: Start ElasticSearch
  service:
    name: elasticsearch
    state: restarted
